[window]

dimensions = { columns = 110, lines = 35 }

resize_increments = true

opacity = 0.95

[font]
normal.family = "Cascadia Code"
size = 12

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
{ key = "F11", mods = "Control|Shift", action = "ToggleFullscreen" },
{ key = "C", mods = "Control|Shift", action = "Copy" },
{ key = "V", mods = "Control|Shift", action = "Paste" },
{ key = "+", mods = "Control|Shift", action = "IncreaseFontSize" },
{ key = "-", mods = "Control|Shift", action = "DecreaseFontSize" },
{ key = "0", mods = "Control|Shift", action = "ResetFontSize" },
{ key = "PageUp", mods = "Control|Shift", action = "ScrollHalfPageUp" },
{ key = "PageDown", mods = "Control|Shift", action = "ScrollHalfPageDown" },
{ key = "F", mods = "Control|Shift", action = "SearchBackward" },
]
