[window]

resize_increments = true

opacity = 0.90

decorations = "None"

dynamic_padding = true
padding = { x = 3, y = 3 }

[font]
normal.family = "Bitstream Vera Sans Mono"
size = 13

[selection]
save_to_clipboard = true

[env]
TERM = "xterm-256color"

[keyboard]
bindings = [
{ key = "F11", mods = "Control|Shift", action = "ToggleFullscreen" },
{ key = "C", mods = "Control|Shift", action = "Copy" },
{ key = "V", mods = "Control|Shift", action = "Paste" },
{ key = "+", mods = "Control|Shift", action = "IncreaseFontSize" },
{ key = "-", mods = "Control|Shift", action = "DecreaseFontSize" },
{ key = "0", mods = "Control|Shift", action = "ResetFontSize" },
{ key = "PageUp", mods = "Control|Shift", action = "ScrollHalfPageUp" },
{ key = "PageDown", mods = "Control|Shift", action = "ScrollHalfPageDown" },
{ key = "F", mods = "Control|Shift", action = "SearchBackward" },
]

# Colors (Tomorrow Night Bright)

# Default colors
[colors.primary]
background = '#000000'
foreground = '#eaeaea'

# Normal colors
[colors.normal]
black   = '#000000'
red     = '#d54e53'
green   = '#b9ca4a'
yellow  = '#e6c547'
blue    = '#7aa6da'
magenta = '#c397d8'
cyan    = '#70c0ba'
white   = '#424242'

# Bright colors
[colors.bright]
black   = '#666666'
red     = '#ff3334'
green   = '#9ec400'
yellow  = '#e7c547'
blue    = '#7aa6da'
magenta = '#b77ee0'
cyan    = '#54ced6'
white   = '#2a2a2a'
