$font = Noto Sans

general {
	hide_cursor = false
}

background {
	path = /home/gabriel/pictures/wallpapers/share/other-irl/iguassu-waterfalls.jpg
}

input-field {
	size = 20%, 5%
	outline_thickness = 0

	inner_color = 0x00000000
	check_color = 0xfff0c674
	fail_color = 0xcc6666

	font_color = 0xff000000
	fade_on_empty = false
	rounding = 15

	font_family = $font
	placeholder_text = 
	fail_text = $PAMFAIL

	dots_spacing = 0.3

	position = 0, -20
	halign = center
	valign = center
}
