# -*- after-save-hook: (org-babel-tangle) -*-
#+PROPERTY: header-args:emacs-lisp :exports code :results none :tangle init.el

* Gabriel's Emacs configuration
This is my Emacs configuration. Enjoy.

Most of the setup is tangled to the file ~init.el~ itself. Some things are tangled to ~early-init.el~ instead to improve startup time.

** Lexical binding
Supresses the annoying error message.

#+BEGIN_SRC emacs-lisp
;;; -*- lexical-binding: t; -*-
#+END_SRC

Also for ~early-init.el~.

#+BEGIN_SRC emacs-lisp :tangle early-init.el
;;; -*- lexical-binding: t; -*-
#+END_SRC

** Garbage collection
Disables garbage collection while loading configuration, and re-enables it right afterwards.

#+BEGIN_SRC emacs-lisp :tangle early-init.el
(setq gc-cons-threshold most-positive-fixnum)
(add-hook 'emacs-startup-hook
          (lambda () (setq gc-cons-threshold (* 50 1024 1024))))
#+END_SRC

Inhibits startup, splash, etc.

#+BEGIN_SRC emacs-lisp :tangle early-init.el
(setq inhibit-splash-screen t)
(setq inhibit-startup-screen t)
(setq inhibit-startup-message t)
(setq inhibit-startup-buffer-menu t)
#+END_SRC

Increases native compilation optimization.

#+BEGIN_SRC emacs-lisp :tangle early-init.el
(setq native-comp-speed 3)
#+END_SRC

** Package management configuration
Nowadays, Emacs already comes with ~use-package~. But we still bootstrap it here as it costs us nothing and we need to setup it anyways.

#+BEGIN_SRC emacs-lisp
(require 'package)

(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/") t)

(package-initialize)

(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

(require 'use-package)

(setq use-package-always-ensure t)
#+END_SRC

Enables support for diminishing modes.

#+BEGIN_SRC emacs-lisp
(use-package diminish
  :init
  (diminish 'visual-line-mode)
  (diminish 'abbrev-mode))
#+END_SRC

** Appearance
*** Basics
Unclutter the UI and stop the blinking cursor.

#+BEGIN_SRC emacs-lisp :tangle early-init.el
(menu-bar-mode -1)
(tool-bar-mode -1)
(scroll-bar-mode -1)
(blink-cursor-mode -1)
#+END_SRC

Prettify symbols.

#+BEGIN_SRC emacs-lisp
(global-prettify-symbols-mode 1)
#+END_SRC

*** Theme, fonts and modeline
Modus Vivendi is great: very dark, very readable, and the best: builtin. We need to be aware it resets the fonts we use.

#+BEGIN_SRC emacs-lisp :tangle early-init.el
(require-theme 'modus-themes)
(setq modus-themes-italic-constructs t)
(setq modus-themes-mixed-fonts t)
(setq modus-themes-headings
      '((1 . (1.5))
        (2 . (1.3))
	(3 . (1.1))))
(setq modus-themes-variable-pitch-ui t)
(add-hook
 'modus-themes-after-load-theme-hook
 (lambda ()
   (set-face-attribute 'default nil :family
		       "Source Code Pro" :height 130)
   (set-face-attribute 'fixed-pitch nil :family
		       "Source Code Pro" :height 130)
   (set-face-attribute 'variable-pitch nil :family
		       "Inter Display" :height 130)))
(modus-themes-load-theme 'modus-vivendi)
#+END_SRC

Make some reading modes use variable text. Help mode variable pitch is only enabled in actual help buffers, because various modes use the help mode and they usually don't look good with variable pitch.

#+BEGIN_SRC emacs-lisp
(add-hook 'help-mode-hook #'variable-pitch-mode)
(add-hook 'package-menu-mode-hook #'variable-pitch-mode)
(add-hook 'Man-mode-hook #'variable-pitch-mode)
#+END_SRC

Modeline.

#+BEGIN_SRC emacs-lisp
(setq display-time-interval 20)
(setq display-time-day-and-date t)
(setq display-time-24hr-format t)
(display-time-mode 1)
(column-number-mode 1)
#+END_SRC

*** Olivetti
Olivetti mode makes text balanced in relation to the window margins, so it occuppies the center instead of being left-aligned.

#+BEGIN_SRC emacs-lisp
(use-package olivetti
  :hook (prog-mode text-mode))
#+END_SRC

** Behaviour
*** Basics
Short answers, fill column, don't make backups.

#+BEGIN_SRC emacs-lisp
(defalias 'yes-or-no-p 'y-or-n-p)
(setopt use-short-answers t)

(setq-default fill-column 80)

(setq make-backup-files nil)
#+END_SRC

Move custom elsewhere.

#+BEGIN_SRC emacs-lisp
(setq custom-file (expand-file-name "custom.el" user-emacs-directory))
(load custom-file 'noerror)
#+END_SRC

Disable the audible bell.

#+BEGIN_SRC emacs-lisp
(setq ring-bell-function 'ignore)
#+END_SRC

Setup auth sources.

#+BEGIN_SRC emacs-lisp
(setq auth-sources '("~/.authinfo.gpg"))
#+END_SRC

Emacs has a very low default nesting limit that's commonly exceeded even on builtin functionality like TRAMP.

#+BEGIN_SRC emacs-lisp
(setq max-lisp-eval-depth 10000)
#+END_SRC

*** Compile mode
No default command, colorize the buffer.

#+BEGIN_SRC emacs-lisp
(setq-default compile-command "")

(require 'ansi-color)
(defun colorize-compilation ()
  "Colorize from `compilation-filter-start' to `point'."
  (let ((inhibit-read-only t))
    (ansi-color-apply-on-region
     compilation-filter-start (point))))

(add-hook 'compilation-filter-hook
          #'colorize-compilation)
#+END_SRC

*** Minibuffer
Makes the minibuffer much nicer.

#+BEGIN_SRC emacs-lisp
(use-package vertico
  :custom
  (enable-recursive-minibuffers t)
  (read-extended-command-predicate #'command-completion-default-include-p)
  (completion-styles '(basic substring partial-completion flex))
  (vertico-cycle t)
  :hook after-init)
(use-package vertico-directory
  :after vertico
  :ensure nil
  :bind (:map vertico-map
              ("RET" . vertico-directory-enter)
              ("DEL" . vertico-directory-delete-char)
              ("M-DEL" . vertico-directory-delete-word))
  :hook (rfn-eshadow-update-overlay . vertico-directory-tidy))
(use-package vertico-mouse
  :after vertico
  :ensure nil
  :hook after-init)
(use-package marginalia
  :hook after-init)
#+END_SRC

*** Windows
Move windows with meta. Makes C-v and M-v to move by half pages instead of full ones.

#+BEGIN_SRC emacs-lisp
(windmove-default-keybindings 'meta)

(defun window-half-height ()
  (max 1 (/ (1- (window-height (selected-window))) 2)))

(defun scroll-up-half ()
  (interactive)
  (scroll-up (window-half-height)))

(defun scroll-down-half ()
  (interactive)
  (scroll-down (window-half-height)))

(global-set-key (kbd "C-v") #'scroll-up-half)
(global-set-key (kbd "M-v") #'scroll-down-half)
#+END_SRC

** Editor configuration
*** Basics
Show trailing whitespaces, but not on some weird buffers of course. Display line numbers and fill column in all actual editing modes. Scroll nicely. Save history and recent files.

#+BEGIN_SRC emacs-lisp
(defun prog-and-text-mode-setup ()
  (display-fill-column-indicator-mode t)
  (setq show-trailing-whitespace t))
(add-hook 'prog-mode-hook #'prog-and-text-mode-setup)
(add-hook 'text-mode-hook #'prog-and-text-mode-setup)

(setq scroll-step 1)
(setq scroll-conservatively 100000)

(savehist-mode 1)
(recentf-mode 1)
#+END_SRC

*** Respect ~.editorconfig~ files.
#+BEGIN_SRC emacs-lisp
(use-package editorconfig
  :hook after-init)
#+END_SRC

*** Electric
Electric, auto-fill and selection deletion.

#+BEGIN_SRC emacs-lisp
(electric-indent-mode t)
(electric-pair-mode t)
(add-hook 'text-mode-hook
  	  (lambda ()
  	    (auto-fill-mode t)))
(delete-selection-mode t)
#+END_SRC

*** Xrefs
So the editor is a little less dumb.

#+BEGIN_SRC emacs-lisp
(use-package dumb-jump
  :custom (dumb-jump-prefer-searcher 'rg)
  :bind ("C-c 2" . xref-find-references-and-replace)
  :hook (prog-mode . (lambda ()
		       (add-to-list
			'xref-backend-functions
			#'dumb-jump-xref-activate))))
#+END_SRC

*** Searching
Ripgrep is fast. Also, the package automatically configures ~wgrep~ for us and other niceties.

#+BEGIN_SRC emacs-lisp
(use-package rg
  :bind (("C-c /" . rg))
  :config
  (rg-enable-default-bindings))
#+END_SRC

*** Project
Project configurations.

#+BEGIN_SRC emacs-lisp
(use-package project
  :ensure nil
  :bind (("C-c c" . project-compile)
	 ("C-c r" . project-async-shell-command)))
#+END_SRC

** Utilities
*** Magit
The best git UI in the world.

#+BEGIN_SRC emacs-lisp
(use-package magit
  :bind (("C-x g" . magit-status))
  :commands (magit-status magit-dispatch magit-file-dispatch))
#+END_SRC

It's better to use ~forge~ than ~magit-gh~. ~forge~ is very complete.

#+BEGIN_SRC emacs-lisp
(use-package forge
  :after magit)
#+END_SRC

*** Dired
File management.

#+BEGIN_SRC emacs-lisp
(setq dired-kill-when-opening-new-dired-buffer t)
(setq dired-delete-by-moving-to-trash t)
(setq dired-listing-switches "-lahD --group-directories-first")
(setq dired-dwim-target t)
(use-package async
  :hook (after-init . dired-async-mode))
#+END_SRC

Enhanced appearance.

#+BEGIN_SRC emacs-lisp
(use-package diredfl
  :hook (after-init . diredfl-global-mode))
#+END_SRC

*** Eat
Eat is the best terminal emulator for Emacs.

#+BEGIN_SRC emacs-lisp
(use-package eat
  :commands (eat eat-other-window))
#+END_SRC

*** HTTPD
Sometimes we need a simple web server.

#+BEGIN_SRC emacs-lisp
(use-package simple-httpd
  :commands (httpd-serve-directory httpd-start httpd-stop))
#+END_SRC

*** Music
#+BEGIN_SRC emacs-lisp
(use-package emms
  :commands (emms emms-browser)
  :bind (("C-c m" . emms-browser)
	 ("C-c M" . emms))
  :custom
  (emms-player-list '(emms-player-mpd))
  (emms-volume-change-functions '(emms-volume-mpd-change))
  :config
  (emms-all)
  (emms-player-mpd-connect)
  (emms-mode-line-mode -1))
#+END_SRC

*** Email
For reading, I use ~mu4e~. The messages are fetched via ~mbsync~. Both need to be installed system-wide. The ~mbsync~ package sometimes is called ~isync~. For sending, I use ~msmtp~. Also needed to be installed system-wide. It's symlinked to ~sendmail~.

#+BEGIN_SRC emacs-lisp
(use-package mu4e
  :ensure nil
  :bind (("C-c e" . mu4e))
  :config
  (setq mu4e-change-filenames-when-moving t)
  (setq mu4e-update-interval 600)
  (setq mu4e-get-mail-command "mbsync -a")
  (setq mu4e-maildir "~/mail")
  (setq mu4e-compose-signature "Please no HTML,\n~ Gabriel G. de Brito")
  (setq send-mail-function 'sendmail-send-it)
  (setq mail-user-agent 'mu4e-user-agent)
  (setq read-mail-command 'mu4e)
  (setq mail-specify-envelope-from t)
  (setq message-sendmail-envelope-from 'header)
  (setq mail-envelope-from 'header)
  (setq mu4e-contexts (list
		  (make-mu4e-context
		   :name "icloud"
		   :match-func
		   (lambda (msg)
		     (when msg
		       (string-prefix-p
			"/icloud" (mu4e-message-field msg :maildir))))
		   :vars '((user-mail-address . "me@gboncoffee.dev.br")
			   (user-full-name . "Gabriel de Brito")
			   (mu4e-drafts-folder  . "/icloud/Drafts")
			   (mu4e-sent-folder  . "/icloud/Sent")
			   (mu4e-trash-folder  . "/icloud/Trash")))
		  (make-mu4e-context
		   :name "dinf"
		   :match-func
		   (lambda (msg)
		     (when msg
		       (string-prefix-p
			"/dinf" (mu4e-message-field msg :maildir))))
		   :vars '((user-mail-address . "ggb23@inf.ufpr.br")
			   (user-full-name . "Gabriel de Brito")
			   (mu4e-drafts-folder  . "/dinf/Drafts")
			   (mu4e-sent-folder  . "/dinf/Sent")
			   (mu4e-trash-folder  . "/dinf/Trash")))))
  (setq mu4e-maildir-shortcuts
   '(("/icloud/inbox" . ?i)
     ("/dinf/inbox" . ?d)))
  (setq mu4e-context-policy 'pick-first)
  (setq mml-secure-openpgp-signers '("ABE72DFCAD2D5333FE3F8912F6C1E4A22E8C1F3D"))
  (add-hook 'message-send-hook 'mml-secure-message-sign-pgpmime))
#+END_SRC

*** Miscelaneous
Better support for PDF files.

#+BEGIN_SRC emacs-lisp
(use-package pdf-tools
  :mode ("\\.pdf\\'" . pdf-view-mode))
#+END_SRC

Better separation of shell commands.

#+BEGIN_SRC emacs-lisp
(use-package shell-command-x
  :diminish shell-command-x
  :hook after-init)
#+END_SRC

** Language specific configuration
*** Go
Basic support.

#+BEGIN_SRC emacs-lisp
(use-package go-mode
  :mode "\\.go\\'"
  :hook
  (go-mode . (lambda ()
	       (setq tab-width 4)
	       (setq indent-tabs-mode t))))
#+END_SRC

Eldoc.

#+BEGIN_SRC emacs-lisp
(use-package go-eldoc
  :after go-mode
  :hook (go-mode . go-eldoc-setup))
#+END_SRC

*** C/C++
Use ~simpc-mode~ because native Emacs C/C++ modes are terribly slow.

#+BEGIN_SRC emacs-lisp
(use-package simpc-mode
  :mode "\\.[hc]\\(pp\\)?\\'"
  :commands simpc-mode
  :vc (:url "https://github.com/rexim/simpc-mode" :rev :newest)
  :hook (simpc-mode . (lambda ()
			(setq tab-width 4)
			(setq indent-tabs-mode nil)))
  :custom
  (c-basic-offset 4)
  (c-default-style "linux")
  (c-tab-always-indent 'complete))
#+END_SRC

*** Pascal
#+BEGIN_SRC emacs-lisp
(setq-default pascal-indent-level 4)
(setq-default pascal-tab-always-indent 'complete)
(add-hook 'pascal-mode-hook
      	  (lambda ()
      	    (setq tab-width 4)
      	    (setq pascal-indent-level 4)
      	    (setq pascal-auto-lineup '())
      	    (setq indent-tabs-mode nil)))
#+END_SRC

*** Web
#+BEGIN_SRC emacs-lisp
(use-package web-mode
  :mode "\\.html?\\'")
#+END_SRC

*** Markdown
#+BEGIN_SRC emacs-lisp
(use-package markdown-mode
  :mode "\\.md\\'")
#+END_SRC

*** ASM
#+BEGIN_SRC emacs-lisp
(use-package nasm-mode
  :mode ("\\.asm\\'" "\\.s\\'"))
#+END_SRC

*** Zig
#+BEGIN_SRC emacs-lisp
(use-package zig-mode
  :mode "\\.zig\\'")
#+END_SRC

*** Odin
#+BEGIN_SRC emacs-lisp
(use-package odin-mode
  :mode "\\.odin\\'"
  :commands odin-mode
  :vc (:url "https://github.com/mattt-b/odin-mode.git"
      	    :rev :last-release)
  :hook (odin-mode . (lambda ()
		       (setq-local indent-tabs-mode t)
		       (indent-tabs-mode 1)
		       (setq-local tab-width 8)
		       (setq-local js-indent-level 8)
		       (setq-local fill-column 100))))
#+END_SRC

*** Elixir
#+BEGIN_SRC emacs-lisp
(use-package elixir-mode
  :mode ("\\.ex\\'" "\\.exs\\'"))
#+END_SRC

Inferior mode.

#+BEGIN_SRC emacs-lisp
(use-package inf-elixir
  :after elixir-mode
  :hook (elixir-mode . inf-elixir-minor-mode))
#+END_SRC

*** Erlang
#+BEGIN_SRC emacs-lisp
(use-package erlang
  :mode "\\.erl\\'")
#+END_SRC

*** Haskell
#+BEGIN_SRC emacs-lisp
(use-package haskell-mode
  :mode "\\.hs\\'"
  :custom
  (haskell-stylish-on-save t))
#+END_SRC

*** Rust
#+BEGIN_SRC emacs-lisp
(use-package rust-mode
  :mode "\\.rs\\'")
#+END_SRC

*** Verilog
#+BEGIN_SRC emacs-lisp
(setq verilog-case-indent 2)
(setq verilog-cexp-indent 2)
(setq verilog-indent-level 2)
(setq verilog-indent-level-module 2)
(setq verilog-indent-level-directive 2)
(setq verilog-indent-level-behavioral 2)
(setq verilog-indent-level-declaration 2)
(setq verilog-auto-lineup nil)
(setq verilog-indent-lists nil)
(add-hook 'verilog-mode-hook
	  (lambda ()
	    (indent-tabs-mode 0)
	    (setq-local tab-width 2)))
#+END_SRC

*** Lua
#+BEGIN_SRC emacs-lisp
(use-package lua-mode
  :mode "\\.lua\\'")
#+END_SRC

*** Common Lisp
#+BEGIN_SRC emacs-lisp
(add-to-list 'auto-mode-alist '("\\.cl\\'" . lisp-mode))
#+END_SRC

*** Formatters for (almost) all the above
#+BEGIN_SRC emacs-lisp
(use-package format-all
  :diminish format-all-mode
  :hook
  (prog-mode . format-all-mode)
  (text-mode . format-all-mode)
  :custom
  (format-all-formatters
   '(("Haskell" (stylish-haskell))
     ("Go" (gofmt "-s"))
     ("Elixir" (mix-format))
     ("Emacs Lisp" (emacs-lisp))
     ("LaTeX" (latexindent))
     ("BibTex" (emacs-bibtex))
     ("Rust" (rustfmt))
     ("Zig" (zig))
     ("Verilog" (verible))
     ("SystemVerilog" (verible)))))

(use-package reformatter
  :init
  (reformatter-define odin-format
    :program "odinfmt"
    :args '("-stdin"))
  (add-hook 'odin-mode-hook #'odin-format-on-save-mode)
  (reformatter-define clang-format
    :program "clang-format")
  (add-hook 'simpc-mode-hook #'clang-format-on-save-mode))
#+END_SRC

*** Minor languages without builtin-support
#+BEGIN_SRC emacs-lisp
(use-package yaml-mode
  :mode "\\.yaml\\'")
#+END_SRC

** Org mode
*** Basic
Setup ~org-directory~ and ~org-agenda-files~.

#+BEGIN_SRC emacs-lisp
(setq org-directory "~/org")
(setq org-agenda-files
      (list (expand-file-name "inbox.org" org-directory)))
#+END_SRC

*** Appearance/Indenting
Visual line, indent, etc.

#+BEGIN_SRC emacs-lisp
(add-hook 'org-mode-hook
	  (lambda ()
	    (visual-line-mode 1)
	    (org-indent-mode)
	    (display-fill-column-indicator-mode -1)
	    (variable-pitch-mode 1)
	    (auto-fill-mode -1)))
#+END_SRC

Pretty.

#+BEGIN_SRC emacs-lisp
(use-package org-superstar
  :hook (org-mode . org-superstar-mode))
#+END_SRC

Hide and fontify everything.

#+BEGIN_SRC emacs-lisp
(setq org-highlight-latex-and-related '(latex script))
(setq-default org-edit-src-content-indentation 0)
(setq-default org-hide-macro-markers t)
(setq-default org-hide-emphasis-markers t)
(setq-default org-hide-block-startup t)
(setq-default org-hide-drawer-startup t)
(setq-default org-startup-folded 'fold)
(setq org-hidden-keywords '(title))
(setq org-superstar-leading-bullet ?\s)
#+END_SRC

Function to count the amount of ~.~ characters in the current line, because I write poetry and like to use it to separate syllables.

#+BEGIN_SRC emacs-lisp
(defun count-dots-in-line ()
  "Count the amount of . characters in the current line"
  (interactive)
  (save-excursion
    (let* ((start (line-beginning-position))
           (end   (line-end-position))
           (count (count-matches "\\." start end)))
      (message "%d" count))))
#+END_SRC

Another function to remove them.

#+BEGIN_SRC emacs-lisp
(defun remove-dots-in-line ()
  "Remove all . characters from the current line."
  (interactive)
  (save-excursion
    (let ((start (line-beginning-position))
          (end (line-end-position)))
      (goto-char start)
      (while (search-forward "." end t)
        (replace-match "" nil t)
        ;; The line became shorter, so keep END in sync.
        (setq end (1- end))))))
#+END_SRC

Bind them in Org mode.

#+BEGIN_SRC emacs-lisp
(with-eval-after-load 'org
  (define-key org-mode-map (kbd "C-c f") #'count-dots-in-line)
  (define-key org-mode-map (kbd "C-c d") #'remove-dots-in-line))
#+END_SRC

*** Beamer
#+BEGIN_SRC emacs-lisp
(use-package ox-beamer-lecture
  :defer t)
#+END_SRC
