#+PROPERTY: header-args:emacs-lisp :tangle config.el

* Gabriel's Emacs configuration
This is my Emacs configuration. Enjoy.

** Package management configuration
Nowadays, Emacs already comes with ~use-package~. But we still bootstrap it here as it costs us nothing and we need to setup it anyways.

#+BEGIN_SRC emacs-lisp
(require 'package)

(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/") t)

(package-initialize)

(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

(require 'use-package)

(setq use-package-always-ensure t)
#+END_SRC

Enables support for diminishing modes.

#+BEGIN_SRC emacs-lisp
(use-package diminish
  :init
  (diminish 'visual-line-mode)
  (diminish 'abbrev-mode))
#+END_SRC

** Appearance
*** Basics
Unclutter the UI, stop the blinking cursor, don't jump text when the width changes, no startup screen.

#+BEGIN_SRC emacs-lisp
(menu-bar-mode -1)
(tool-bar-mode -1)
(scroll-bar-mode -1)
(blink-cursor-mode -1)

(setq-default display-line-numbers-width 3)
(setq inhibit-startup-screen t)
#+END_SRC

Prettify symbols.

#+BEGIN_SRC emacs-lisp
(global-prettify-symbols-mode 1)
#+END_SRC

*** Fonts
Hack and Noto Sans. Use variable pitch for Org mode.

#+BEGIN_SRC emacs-lisp
(set-face-attribute 'default nil :family "Hack" :height 110)
(set-face-attribute 'fixed-pitch nil :family "Hack" :height 110)
(set-face-attribute 'variable-pitch nil :family "Noto Sans" :height 130)
#+END_SRC

Make some reading modes use variable text. Help mode variable pitch is only enabled in actual help buffers, because various modes use the help mode and they usually don't look good with variable pitch.

#+BEGIN_SRC emacs-lisp
(add-hook 'help-mode-hook #'variable-pitch-mode)
(add-hook 'package-menu-mode-hook #'variable-pitch-mode)
(add-hook 'Man-mode-hook #'variable-pitch-mode)
#+END_SRC

*** Theme and modeline
The theme I like is Tomorrow.

#+BEGIN_SRC emacs-lisp
(use-package base16-theme
  :config
  (setq-default base16-theme-highlight-mode-line t)
  (load-theme 'base16-tomorrow-night t))
#+END_SRC

Modeline.

#+BEGIN_SRC emacs-lisp
(setq display-time-interval 20)
(setq display-time-day-and-date t)
(setq display-time-24hr-format t)
(display-time-mode 1)
#+END_SRC

Also make the modeline display with variable fonts.

#+BEGIN_SRC emacs-lisp
(set-face-attribute 'mode-line nil :inherit 'variable-pitch)
(set-face-attribute 'mode-line-inactive nil :inherit 'variable-pitch)
#+END_SRC

*** Rainbow
Rainbow delimiters and rainbow mode.

#+BEGIN_SRC emacs-lisp
(use-package rainbow-delimiters
  :hook (prog-mode-hook . rainbow-delimiters-mode))

(use-package rainbow-mode
  :diminish rainbow-mode
  :hook (prog-mode-hook . rainbow-mode))
#+END_SRC

** Behaviour
*** Basics
Short answers, fill column, don't make backups.

#+BEGIN_SRC emacs-lisp
(defalias 'yes-or-no-p 'y-or-n-p)
(setopt use-short-answers t)

(setq-default fill-column 80)

(setq make-backup-files nil)
#+END_SRC

Move custom elsewhere.

#+BEGIN_SRC emacs-lisp
(setq custom-file (expand-file-name "custom.el" user-emacs-directory))
(load custom-file 'noerror)
#+END_SRC

Disable the audible bell.

#+BEGIN_SRC emacs-lisp
(setq ring-bell-function 'ignore)
#+END_SRC

Setup auth sources.

#+BEGIN_SRC emacs-lisp
(setq auth-sources '("~/.authinfo.gpg"))
#+END_SRC

Emacs has a very low default nesting limit that's commonly exceeded even on builtin functionality like TRAMP.

#+BEGIN_SRC emacs-lisp
(setq max-lisp-eval-depth 10000)
#+END_SRC

*** Compile mode
No default command, colorize the buffer.

#+BEGIN_SRC emacs-lisp
(setq-default compile-command "")

(require 'ansi-color)
(defun colorize-compilation ()
  "Colorize from `compilation-filter-start' to `point'."
  (let ((inhibit-read-only t))
    (ansi-color-apply-on-region
     compilation-filter-start (point))))

(add-hook 'compilation-filter-hook
          #'colorize-compilation)
#+END_SRC

*** Minibuffer
Makes the minibuffer much nicer.

#+BEGIN_SRC emacs-lisp
(setq enable-recursive-minibuffers t)
(setq read-extended-command-predicate #'command-completion-default-include-p)
(use-package vertico
  :init
  (setq completion-styles '(basic substring partial-completion flex))
  (setq vertico-cycle t)
  (vertico-mode 1))
(use-package vertico-directory
  :after vertico
  :ensure nil
  :bind (:map vertico-map
              ("RET" . vertico-directory-enter)
              ("DEL" . vertico-directory-delete-char)
              ("M-DEL" . vertico-directory-delete-word))
  :hook (rfn-eshadow-update-overlay . vertico-directory-tidy))
(use-package vertico-mouse
  :after vertico
  :ensure nil
  :init
  (vertico-mouse-mode 1))

(use-package marginalia
  :init
  (marginalia-mode 1))
#+END_SRC

*** Windows
Move windows with meta. Makes C-v and M-v to move by half pages instead of full ones.

#+BEGIN_SRC emacs-lisp
(windmove-default-keybindings 'meta)

(defun window-half-height ()
  (max 1 (/ (1- (window-height (selected-window))) 2)))

(defun scroll-up-half ()
  (interactive)
  (scroll-up (window-half-height)))

(defun scroll-down-half ()
  (interactive)
  (scroll-down (window-half-height)))

(global-set-key (kbd "C-v") #'scroll-up-half)
(global-set-key (kbd "M-v") #'scroll-down-half)
#+END_SRC

** Editor configuration
*** Basics
Show trailing whitespaces, but not on some weird buffers of course. Display line numbers and fill column in all actual editing modes. Scroll nicely. Save history and recent files.

#+BEGIN_SRC emacs-lisp
(defun prog-and-text-mode-setup ()
  (display-line-numbers-mode t)
  (display-fill-column-indicator-mode t)
  (setq show-trailing-whitespace t))
(add-hook 'prog-mode-hook #'prog-and-text-mode-setup)
(add-hook 'text-mode-hook #'prog-and-text-mode-setup)

(setq scroll-step 1)
(setq scroll-conservatively 100000)

(savehist-mode 1)
(recentf-mode 1)
#+END_SRC

*** Respect ~.editorconfig~ files.
#+BEGIN_SRC emacs-lisp
(use-package editorconfig
  :config
  (editorconfig-mode t))
#+END_SRC

*** Electric
Electric, auto-fill and selection deletion.

#+BEGIN_SRC emacs-lisp
(electric-indent-mode t)
(electric-pair-mode t)
(add-hook 'text-mode-hook
  	  (lambda ()
  	    (auto-fill-mode t)))
(delete-selection-mode t)
#+END_SRC

*** Multiple cursors
#+BEGIN_SRC emacs-lisp
(use-package multiple-cursors
  :bind (
  	 ("C-S-c" . mc/edit-lines)
  	 ("C->" . #'mc/mark-next-like-this)
  	 ("C-<" . #'mc/mark-previous-like-this)))
#+END_SRC

Fixes org mode.

#+BEGIN_SRC emacs-lisp
(with-eval-after-load 'multiple-cursors
  (dolist (cmd '(org-self-insert-command org-delete-backward-char))
    (add-to-list 'mc/cmds-to-run-for-all cmd)))
#+END_SRC

*** Xrefs
So the editor is a little less dumb.

#+BEGIN_SRC emacs-lisp
(use-package dumb-jump
  :custom (dumb-jump-prefer-searcher 'rg)
  :hook (prog-mode . (lambda ()
		       (add-to-list
			'xref-backend-functions
			#'dumb-jump-xref-activate)))
  :config
  (add-to-list 'xref-backend-functions #'dumb-jump-xref-activate))

(global-set-key (kbd "C-c 2") #'xref-find-references-and-replace)
#+END_SRC

*** Searching
CTRL+F enhances single-buffer searching.

#+BEGIN_SRC emacs-lisp
(use-package ctrlf
  :init
  (setq ctrlf-auto-recenter t)
  (ctrlf-mode 1))
#+END_SRC

Ripgrep is fast. Also, the package automatically configures ~wgrep~ for us and other niceties.

#+BEGIN_SRC emacs-lisp
(use-package rg
  :bind (("C-c /" . rg))
  :init
  (rg-enable-default-bindings))
#+END_SRC

*** Yasnippets
Snippet system.

#+BEGIN_SRC emacs-lisp
(use-package yasnippet
  :diminish yas-minor-mode
  :init
  (yas-global-mode 1))
(use-package yasnippet-snippets)
#+END_SRC

*** Project
Project configurations.

#+BEGIN_SRC emacs-lisp
(use-package project
  :ensure nil
  :bind (("C-c c" . project-compile)
	 ("C-c r" . project-async-shell-command)))
#+END_SRC

** Utilities
*** Magit
The best git UI in the world.

#+BEGIN_SRC emacs-lisp
(use-package magit)
#+END_SRC

It's better to use ~forge~ than ~magit-gh~. ~forge~ is very complete.

#+BEGIN_SRC emacs-lisp
(use-package forge
  :after magit)
#+END_SRC

*** Dired
File management.

#+BEGIN_SRC emacs-lisp
(setq dired-kill-when-opening-new-dired-buffer t)
(setq dired-delete-by-moving-to-trash t)
(setq dired-listing-switches "-aD --group-directories-first")
#+END_SRC

Enhanced appearance.

#+BEGIN_SRC emacs-lisp
(use-package diredfl
  :hook (dired-mode . diredfl-mode))
#+END_SRC

*** Eat
Eat is the best terminal emulator for Emacs.

#+BEGIN_SRC emacs-lisp
(use-package eat)
#+END_SRC

*** HTTPD
Sometimes we need a simple web server.

#+BEGIN_SRC emacs-lisp
(use-package simple-httpd)
#+END_SRC

*** Music
I've used EMMS before but it kept forgetting my database. Now I use the builtin MPD client, so music is actually played by MPD.

#+BEGIN_SRC emacs-lisp
(setq mpc-browser-tags '(Artist Album Playlist))
(global-set-key (kbd "C-c m") #'mpc)
(add-hook 'mpc-mode-hook
	  (lambda ()
	    (local-set-key (kbd "SPC") #'mpc-select-toggle)
	    (local-set-key (kbd "a") #'mpc-playlist-add)
	    (local-set-key (kbd "DEL") #'mpc-playlist-delete)
	    (local-set-key (kbd "n") #'next-line)
	    (local-set-key (kbd "p") #'previous-line)
	    (local-set-key (kbd "P") #'mpc-playlist)
	    (local-set-key (kbd "TAB") #'other-window)
	    (variable-pitch-mode 1)))
#+END_SRC

*** Email

For reading, I use ~mu4e~. The messages are fetched via ~mbsync~. Both need to be installed system-wide. The ~mbsync~ package sometimes is called ~isync~. For sending, I use ~msmtp~. Also needed to be installed system-wide. It's symlinked to ~sendmail~.

#+BEGIN_SRC emacs-lisp
(use-package mu4e
  :ensure nil
  :bind (("C-c e" . mu4e))
  :config
  (setq mu4e-change-filenames-when-moving t)
  (setq mu4e-update-interval 600)
  (setq mu4e-get-mail-command "mbsync -a")
  (setq mu4e-maildir "~/mail")
  (setq mu4e-compose-signature "Please no HTML,\n~ Gabriel G. de Brito")

  (setq send-mail-function 'sendmail-send-it)
  (setq mail-user-agent 'mu4e-user-agent)
  (set-variable 'read-mail-command 'mu4e)
  (setq mail-specify-envelope-from t)
  (setq message-sendmail-envelope-from 'header)
  (setq mail-envelope-from 'header)

  (setq mu4e-contexts (list
		       (make-mu4e-context
			:name "icloud"
			:match-func
			(lambda (msg)
			  (when msg
			    (string-prefix-p "/icloud" (mu4e-message-field msg :maildir))))
			:vars '((user-mail-address . "me@gboncoffee.dev.br")
				(user-full-name . "Gabriel de Brito")
				(mu4e-drafts-folder  . "/icloud/Drafts")
				(mu4e-sent-folder  . "/icloud/Sent")
				(mu4e-trash-folder  . "/icloud/Trash")))
		       (make-mu4e-context
			:name "dinf"
			:match-func
			(lambda (msg)
			  (when msg
			    (string-prefix-p "/dinf" (mu4e-message-field msg :maildir))))
			:vars '((user-mail-address . "ggb23@inf.ufpr.br")
				(user-full-name . "Gabriel de Brito")
				(mu4e-drafts-folder  . "/dinf/Drafts")
				(mu4e-sent-folder  . "/dinf/Sent")
				(mu4e-trash-folder  . "/dinf/Trash")))))

  (setq mu4e-maildir-shortcuts
	'(("/icloud/inbox" . ?i)
	  ("/dinf/inbox" . ?d)))

  (setq mu4e-context-policy 'pick-first)

  (setq mml-secure-openpgp-signers '("ABE72DFCAD2D5333FE3F8912F6C1E4A22E8C1F3D"))
  (add-hook 'message-send-hook 'mml-secure-message-sign-pgpmime))
#+END_SRC

*** GPTel
LLM client.

#+BEGIN_SRC emacs-lisp
(use-package gptel
  :init
  (setq gptel-default-mode #'org-mode)
  (setq gptel-model 'gpt-5-mini)
  (setq gptel-backend (gptel-make-gh-copilot "Copilot")))
#+END_SRC

*** Miscelaneous
Lice to add licenses.

#+BEGIN_SRC emacs-lisp
(use-package lice)
#+END_SRC

Better support for PDF files.

#+BEGIN_SRC emacs-lisp
(use-package pdf-tools)
#+END_SRC

Better separation of shell commands.

#+BEGIN_SRC emacs-lisp
(use-package shell-command-x
  :diminish shell-command-x
  :init
  (shell-command-x-mode 1))
#+END_SRC

** Language specific configuration
*** Go
Basic support.

#+BEGIN_SRC emacs-lisp
(use-package go-mode
  :hook
  (go-mode-hook . (lambda ()
		    (setq tab-width 4)
		    (setq indent-tabs-mode t))))
#+END_SRC

Eldoc.

#+BEGIN_SRC emacs-lisp
(use-package go-eldoc
  :hook (go-mode-hook . go-eldoc-setup))
#+END_SRC

Snippets

#+BEGIN_SRC emacs-lisp
(use-package go-snippets)
#+END_SRC

*** C/C++
#+BEGIN_SRC emacs-lisp
(setq-default c-basic-offset 4)
(setq-default c-default-style "linux")
(setq-default c-tab-always-indent 'complete)
(defun c-configs ()
  (setq tab-width 4)
  (setq indent-tabs-mode nil))
(add-hook 'c-mode-hook #'c-configs)
(add-hook 'c++-mode-hook #'c-configs)
#+END_SRC

*** Pascal
#+BEGIN_SRC emacs-lisp
(setq-default pascal-indent-level 4)
(setq-default pascal-tab-always-indent 'complete)
(add-hook 'pascal-mode-hook
      	  (lambda ()
      	    (setq tab-width 4)
      	    (setq pascal-indent-level 4)
      	    (setq pascal-auto-lineup '())
      	    (setq indent-tabs-mode nil)))
#+END_SRC

*** Web
#+BEGIN_SRC emacs-lisp
(use-package web-mode
  :config
  (add-to-list 'auto-mode-alist '("\\.html?\\'" . web-mode)))
#+END_SRC

*** Markdown
#+BEGIN_SRC emacs-lisp
(use-package markdown-mode)
#+END_SRC

*** ASM
#+BEGIN_SRC emacs-lisp
(use-package nasm-mode
  :config
  (add-to-list 'auto-mode-alist '("\\.asm\\'" . nasm-mode))
  (add-to-list 'auto-mode-alist '("\\.s\\'" . nasm-mode)))
#+END_SRC

*** Zig
#+BEGIN_SRC emacs-lisp
(use-package zig-mode)
#+END_SRC

*** Odin
#+BEGIN_SRC emacs-lisp
(use-package odin-mode
  :commands odin-mode
  :vc (:url "https://github.com/mattt-b/odin-mode.git"
      	    :rev :last-release)
  :hook (odin-mode . (lambda ()
		       (setq-local indent-tabs-mode t)
		       (indent-tabs-mode 1)
		       (setq-local tab-width 8)
		       (setq-local js-indent-level 8)
		       (setq-local fill-column 100))))
#+END_SRC

*** Elixir
#+BEGIN_SRC emacs-lisp
(use-package elixir-mode)
#+END_SRC

Snippets.

#+BEGIN_SRC emacs-lisp
(use-package elixir-yasnippets)
#+END_SRC

Inferior mode.

#+BEGIN_SRC emacs-lisp
(use-package inf-elixir)
#+END_SRC

*** Erlang
#+BEGIN_SRC emacs-lisp
(use-package erlang)
#+END_SRC

*** Haskell
#+BEGIN_SRC emacs-lisp
(use-package haskell-mode
  :config
  (setq haskell-stylish-on-save t))
#+END_SRC

Snippets.

#+BEGIN_SRC emacs-lisp
(use-package haskell-snippets)
#+END_SRC

*** Rust
#+BEGIN_SRC emacs-lisp
(use-package rust-mode)
#+END_SRC

*** Verilog
#+BEGIN_SRC emacs-lisp
(setq verilog-case-indent 2)
(setq verilog-cexp-indent 2)
(setq verilog-indent-level 2)
(setq verilog-indent-level-module 2)
(setq verilog-indent-level-directive 2)
(setq verilog-indent-level-behavioral 2)
(setq verilog-indent-level-declaration 2)
(setq verilog-auto-lineup nil)
(setq verilog-indent-lists nil)
(add-hook 'verilog-mode-hook
	  (lambda ()
	    (indent-tabs-mode 0)
	    (setq-local tab-width 2)))
#+END_SRC

*** Lua
#+BEGIN_SRC emacs-lisp
(use-package lua-mode)
#+END_SRC

*** Formatters for (almost) all the above
#+BEGIN_SRC emacs-lisp
(use-package format-all
  :diminish format-all-mode
  :hook
  (prog-mode-hook . format-all-mode)
  (text-mode-hook . format-all-mode)
  :config
  (setq-default format-all-formatters
		'(("C" (clang-format))
		  ("C++" (clang-format))
		  ("Cuda" (clang-format))
		  ("Haskell" (stylish-haskell))
		  ("Go" (gofmt "-s"))
		  ("Elixir" (mix-format))
		  ("Emacs Lisp" (emacs-lisp))
		  ("LaTeX" (latexindent))
		  ("BibTex" (emacs-bibtex))
		  ("Rust" (rustfmt))
		  ("Zig" (zig))
		  ("Verilog" (verible))
		  ("SystemVerilog" (verible)))))

(use-package reformatter
  :init
  (reformatter-define odin-format
    :program "odinfmt"
    :args '("-stdin"))
  (add-hook 'odin-mode-hook #'odin-format-on-save-mode))
#+END_SRC

*** Minor languages without builtin-support
#+BEGIN_SRC emacs-lisp
(use-package yaml-mode)
#+END_SRC

** Org mode
*** Basic
Setup ~org-directory~ and ~org-agenda-files~.

#+BEGIN_SRC emacs-lisp
(setq org-directory "~/org")
(setq org-agenda-files
      (list (expand-file-name "inbox.org" org-directory)))
#+END_SRC

*** Appearance/Indenting
Visual line, indent, etc.

#+BEGIN_SRC emacs-lisp
(add-hook 'org-mode-hook
	  (lambda ()
	    (visual-line-mode 1)
	    (org-indent-mode)
	    (display-line-numbers-mode -1)
	    (display-fill-column-indicator-mode -1)
	    (auto-fill-mode -1)
	    (variable-pitch-mode 1)))
#+END_SRC

Pretty.

#+BEGIN_SRC emacs-lisp
(use-package org-superstar
  :hook (org-mode-hook . org-superstar-mode))
#+END_SRC

Hide and fontify everything.

#+BEGIN_SRC emacs-lisp
(setq org-highlight-latex-and-related '(latex script))
(setq-default org-edit-src-content-indentation 0)
(setq-default org-hide-macro-markers t)
(setq-default org-hide-emphasis-markers t)
(setq-default org-hide-block-startup t)
(setq-default org-hide-drawer-startup t)
(setq-default org-startup-folded 'fold)
(setq org-hidden-keywords '(title))
(setq org-superstar-leading-bullet ?\s)
#+END_SRC

*** Fonts and faces.
#+BEGIN_SRC emacs-lisp
(setq org-n-level-faces 4)
(set-face-attribute 'org-level-1 nil :height 1.5)
(set-face-attribute 'org-level-2 nil :height 1.35)
(set-face-attribute 'org-level-3 nil :height 1.2)
(set-face-attribute 'org-level-4 nil :height 1.0)

(add-hook 'org-mode-hook
	  (lambda ()
	    (dolist (face '(org-block
			    org-block-begin-line
			    org-block-end-line
			    org-code
			    org-verbatim
			    org-meta-line
			    org-special-keyword
			    org-table
			    org-table-row))
	      (when (facep face)
		(set-face-attribute face nil :inherit 'fixed-pitch)))))
#+END_SRC
